# Generated by Django 2.1.7 on 2019-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GdbAppLabour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_of_temp_labour', models.IntegerField()),
                ('no_of_gdb_labour', models.IntegerField()),
                ('temp_hours', models.IntegerField()),
                ('gdb_hours', models.IntegerField()),
                ('temp_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gdb_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('loss', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_pl', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'gdb_app_labour',
                'managed': False,
            },
        ),
    ]
