# Generated by Django 2.1.7 on 2019-08-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_gdblabour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdblabour',
            options={},
        ),
    ]
