# Generated by Django 2.1.7 on 2019-08-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_size', models.IntegerField(default=0)),
                ('project_unit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_units', models.IntegerField(default=0)),
                ('project_total_units', models.IntegerField(default=0)),
                ('project_total_gallons', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('project_cost_gallon', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('project_cost_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('relationship_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Master')),
            ],
        ),
    ]
