# Generated by Django 2.1.7 on 2019-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='project_total_gallons',
            field=models.IntegerField(default=0),
        ),
    ]
