# Generated by Django 2.1.7 on 2019-08-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20190822_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
