# Generated by Django 2.1.7 on 2019-08-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_master_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartpint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarts', models.IntegerField(default=0)),
                ('pints', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='quartpint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Quartpint'),
        ),
    ]
