# Generated by Django 2.1.7 on 2019-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20190827_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartpint',
            name='project_total_gallons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
