# Generated by Django 2.1.7 on 2019-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20190827_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='project_pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
