# Generated by Django 2.1.7 on 2019-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20190829_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='project_pl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
